production:
  adapter: redis
  url: redis://redistogo:9f3401bc8aed7cb7257d8ea94117646e@greeneye.redistogo.com:10146/
  
development:
  adapter: async
  url: redis://localhost:6379

development:
  adapter: async
  url: redis://localhost:6379
