# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3f80f28307a4deda729ed33bff02dc170a76c90070f2b8abc82049c7c7d61997589272c65d7ce761ef278fd99ef230e8683a5d18c1aa9493756823070cf1f82
  filepicker_api_key: <%= ENV["FILEPICKER_API_KEY"] %>
  business_url: <%= ENV["BUSINESS_URL"] %>
  google_api_key: <%= ENV["GOOGLE_API_KEY"] %>
  action_cable_url: <%= ENV["ACTION_CABLE_URL"] %>

test:
  secret_key_base: a0fbded1070524caee7bf99a3ff02afb61cbda950b5d7e0714a1bb3a61df9a722450c44187f074b50d26b2bfcd91d95f0c6f39ccdd1d7872a65d31530140a057
  filepicker_api_key: <%= ENV["FILEPICKER_API_KEY"] %>
  business_url: <%= ENV["BUSINESS_URL"] %>
  google_api_key: <%= ENV["GOOGLE_API_KEY"] %>
  action_cable_url: <%= ENV["ACTION_CABLE_URL"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  filepicker_api_key: <%= ENV["FILEPICKER_API_KEY"] %>
  business_url: <%= ENV["BUSINESS_URL"] %>
  google_api_key: <%= ENV["GOOGLE_API_KEY"] %>
  action_cable_url: <%= ENV["ACTION_CABLE_URL"] %>
